### ISSUE TITLE
 add max_ls_iter and max_dirichlet_iter as options in model.train

### ISSUE THREAD

**Issue by MagdalenaMat** [calico/spatial_lda#14]
When increasing the number of topics to be discovered I get an Exception:
```
Exception: Stopping in admm.newton_regularized_dirichlet.
```

As you suggested It could be fixed by increasing the number of line search iterations (`ls_iter` in the `admm.newton_regularized_dirichlet`)  and the number of Dirichlet iterations (`max_diricihlet_iter` in the `admm.admm`).

Could you add these options to the `model.train`, please?

**Comment by z-chen** [comment]
Fixed by #23
